# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'instagramClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
  pod 'Firebase/Analytics'  
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Storage'
  pod 'SDWebImage', '~> 5.0'

  # add pods for desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

  # Pods for instagramClone

end
